FROM golang:1.22.3-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Command to run tests will be specified in docker-compose
CMD ["go", "test", "./tests/...", "-v"] 