source 'https://rubygems.org'

# Jekyll'in kendisi
gem "jekyll", "~> 4.3.2"

# Just the Docs teması
gem "just-the-docs"

# Gerekli eklentiler
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag"
end

# Platform spesifik gemler
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Windows ve JRuby için özel gemler
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Protobuf sorunu için
gem 'google-protobuf', '~> 3.24', platform: :ruby
